"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Express = require("express");
var Helment = require("helmet");
var Cors = require("cors");
var routes_1 = require("./routes");
var middleware_1 = require("./middleware");
var server = Express();
server.use(Helment());
server.use(Express.json());
server.use(Cors());
var generalRestrictedRoute = Express.Router();
generalRestrictedRoute.use(middleware_1.verifyLoggedIn);
generalRestrictedRoute.use('/amenities', routes_1.amenitiesRouter);
generalRestrictedRoute.use('/listings', routes_1.listingsRouter);
generalRestrictedRoute.use('/neighborhoods', routes_1.neighborhoodsRouter);
generalRestrictedRoute.use('/propertyTypes', routes_1.propertyTypesRouter);
generalRestrictedRoute.use('/users', routes_1.usersRouter);
server.use('/api/auth', middleware_1.validateCredentials, routes_1.authRouter);
server.use('/api/restricted', generalRestrictedRoute);
exports.default = server;
